"""
Eisenstein A₂ Lattice Operations — the geometric backbone of constraint theory.

Every point in the complex plane is within ρ = 1/√3 of an A₂ lattice point.
This guarantee underpins the entire unified architecture: bounded error by construction.

The A₂ lattice is generated by {1, ω} where ω = e^{2πi/3} = -1/2 + i√3/2.
Points are represented as integer pairs (a, b) corresponding to a·1 + b·ω.

Example
-------
>>> from constraint_theory_core.lattice import snap, covering_radius, is_safe
>>> pt, err = snap(0.5, 0.3)
>>> err < covering_radius()
True
>>> is_safe(err)
True
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import List, Tuple

# ---------------------------------------------------------------------------
# Constants (derived from first principles)
# ---------------------------------------------------------------------------

SQRT_3: float = math.sqrt(3.0)
"""√3, the fundamental constant of the A₂ lattice."""

OMEGA_RE: float = -0.5
"""Real part of ω = e^{2πi/3}."""

OMEGA_IM: float = SQRT_3 / 2.0
"""Imaginary part of ω."""

COVERING_RADIUS: float = 1.0 / SQRT_3
"""ρ = 1/√3 ≈ 0.577 — max distance from any point to nearest lattice point."""

SAFE_THRESHOLD: float = COVERING_RADIUS / 2.0
"""ρ/2 ≈ 0.289 — below this, snap is guaranteed safe."""

# ---------------------------------------------------------------------------
# Dodecet encoding (12 nearest-neighbor directions on A₂)
# ---------------------------------------------------------------------------

DODECET_DIRECTIONS: List[Tuple[int, int]] = [
    (1, 0), (0, 1), (-1, 1), (-1, 0), (0, -1), (1, -1),
    (2, -1), (1, -2), (-1, -1), (-2, 1), (-1, 2), (1, 1),
]
"""The 12 minimal nonzero vectors of the A₂ lattice."""

# 48 Pythagorean directions (exact angles with rational sin/cos)
# log2(48) = 5.585 bits — maximum information per bit for 16-bit integers
DIRECTION_COUNT: int = 48


# ---------------------------------------------------------------------------
# Core types
# ---------------------------------------------------------------------------

@dataclass(frozen=True, slots=True)
class A2Point:
    """A point on the A₂ (Eisenstein) lattice: a·1 + b·ω.

    Attributes
    ----------
    a : int
        Coefficient of basis vector 1.
    b : int
        Coefficient of basis vector ω = e^{2πi/3}.
    """
    a: int
    b: int

    def __add__(self, other: A2Point) -> A2Point:
        return A2Point(self.a + other.a, self.b + other.b)

    def __sub__(self, other: A2Point) -> A2Point:
        return A2Point(self.a - other.a, self.b - other.b)

    def __neg__(self) -> A2Point:
        return A2Point(-self.a, -self.b)

    def norm_sq(self) -> int:
        """Squared Eisenstein norm: a² - ab + b².

        This is always non-negative and equals |z|² where
        z = a + bω in the complex plane.
        """
        return self.a * self.a - self.a * self.b + self.b * self.b

    def to_complex(self) -> Tuple[float, float]:
        """Convert to Cartesian (x, y) in the complex plane."""
        x = self.a + self.b * OMEGA_RE
        y = self.b * OMEGA_IM
        return (x, y)


# ---------------------------------------------------------------------------
# Core operations
# ---------------------------------------------------------------------------

def snap(x: float, y: float) -> Tuple[A2Point, float]:
    """Snap a point (x, y) to the nearest A₂ lattice point.

    Parameters
    ----------
    x : float
        Real coordinate.
    y : float
        Imaginary coordinate.

    Returns
    -------
    Tuple[A2Point, float]
        The nearest lattice point and the quantization error.

    Notes
    -----
    Error is guaranteed to be ≤ ρ = 1/√3 ≈ 0.577 by the covering property.

    Examples
    --------
    >>> pt, err = snap(0.5, 0.3)
    >>> err <= 1.0 / math.sqrt(3)
    True
    """
    # Convert Cartesian to lattice coordinates
    # z = x + iy = a + bω = a + b(-1/2 + i√3/2)
    # x = a - b/2,  y = b√3/2
    # b = 2y/√3,  a = x + b/2
    b_f = y / OMEGA_IM  # = 2y/√3
    a_f = x + b_f * 0.5

    # Round to nearest integers
    a = round(a_f)
    b = round(b_f)

    # Check the 4 candidates (a,b), (a±1,b), (a,b±1) for closest
    best = A2Point(a, b)
    best_err = _distance_to(x, y, best)

    for da, db in [(1, 0), (-1, 0), (0, 1), (0, -1), (1, -1), (-1, 1)]:
        candidate = A2Point(a + da, b + db)
        err = _distance_to(x, y, candidate)
        if err < best_err:
            best = candidate
            best_err = err

    return (best, best_err)


def covering_radius() -> float:
    """Return the A₂ covering radius ρ = 1/√3."""
    return COVERING_RADIUS


def is_safe(error: float) -> bool:
    """Check if quantization error is within the safe threshold.

    Safe means error < ρ/2, which guarantees the snap is unambiguous
    (no closer lattice point exists within half the covering radius).
    """
    return error < SAFE_THRESHOLD


def norm_sq(point: A2Point) -> int:
    """Compute squared Eisenstein norm a² - ab + b²."""
    return point.norm_sq()


def decode_dodecet(index: int) -> A2Point:
    """Decode a dodecet index (0-11) to an A₂ direction vector.

    Parameters
    ----------
    index : int
        Dodecet index, 0 ≤ index < 12.

    Returns
    -------
    A2Point
        The direction vector.

    Raises
    ------
    ValueError
        If index is not in [0, 11].
    """
    if not 0 <= index < 12:
        raise ValueError(f"Dodecet index must be 0-11, got {index}")
    a, b = DODECET_DIRECTIONS[index]
    return A2Point(a, b)


def encode_dodecet(point: A2Point) -> int:
    """Encode an A₂ direction vector to a dodecet index.

    Parameters
    ----------
    point : A2Point
        A short lattice vector.

    Returns
    -------
    int
        Dodecet index 0-11.

    Raises
    ------
    ValueError
        If the point is not one of the 12 minimal vectors.
    """
    t = (point.a, point.b)
    try:
        return DODECET_DIRECTIONS.index(t)
    except ValueError:
        raise ValueError(f"({point.a}, {point.b}) is not a dodecet direction")


def vector48_encode(angle: float) -> int:
    """Quantize an angle to one of 48 Pythagorean directions.

    The 48 directions are evenly spaced at 7.5° intervals (360°/48).

    Parameters
    ----------
    angle : float
        Angle in radians.

    Returns
    -------
    int
        Direction index 0-47.
    """
    TWO_PI = 2.0 * math.pi
    # Normalize to [0, 2π)
    normalized = angle % TWO_PI
    index = round(normalized / TWO_PI * DIRECTION_COUNT) % DIRECTION_COUNT
    return index


def vector48_decode(index: int) -> float:
    """Decode a Pythagorean direction index to an angle.

    Parameters
    ----------
    index : int
        Direction index 0-47.

    Returns
    -------
    float
        Angle in radians.
    """
    if not 0 <= index < DIRECTION_COUNT:
        raise ValueError(f"Direction index must be 0-{DIRECTION_COUNT - 1}, got {index}")
    return index * 2.0 * math.pi / DIRECTION_COUNT


def holonomy_product(directions: List[int]) -> int:
    """Compute holonomy around a cycle of directions.

    The holonomy is the sum of direction vectors modulo 48.
    If the result is 0, the cycle is consistent (holonomy-free).

    Parameters
    ----------
    directions : List[int]
        List of direction indices (0-47) forming a cycle.

    Returns
    -------
    int
        Holonomy (sum mod 48). 0 means consistent.
    """
    return sum(directions) % DIRECTION_COUNT


def is_consistent(directions: List[int]) -> bool:
    """Check if a cycle of directions is holonomy-free (consistent).

    Parameters
    ----------
    directions : List[int]
        List of direction indices forming a cycle.

    Returns
    -------
    bool
        True if holonomy is zero (cycle is consistent).
    """
    return holonomy_product(directions) == 0


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _distance_to(x: float, y: float, point: A2Point) -> float:
    """Euclidean distance from (x, y) to a lattice point."""
    px, py = point.to_complex()
    dx = x - px
    dy = y - py
    return math.sqrt(dx * dx + dy * dy)
