"""
Eisenstein A₂ Lattice Operations — the geometric backbone of constraint theory.

Every point in the complex plane is within ρ = 1/√3 of an A₂ lattice point.
This guarantee underpins the entire unified architecture: bounded error by construction.

The A₂ lattice is generated by {1, ω} where ω = e^{2πi/3} = -1/2 + i√3/2.
Points are represented as integer pairs (a, b) corresponding to a·1 + b·ω.

Example
-------
>>> from constraint_theory_core.lattice import snap, covering_radius, is_safe
>>> pt, err = snap(0.5, 0.3)
>>> err < covering_radius()
True
>>> is_safe(err)
True
"""

from __future__ import annotations

import math
from dataclasses import dataclass

# ---------------------------------------------------------------------------
# Constants (derived from first principles)
# ---------------------------------------------------------------------------

SQRT_3: float = math.sqrt(3.0)
"""√3, the fundamental constant of the A₂ lattice."""

OMEGA_RE: float = -0.5
"""Real part of ω = e^{2πi/3}."""

OMEGA_IM: float = SQRT_3 / 2.0
"""Imaginary part of ω."""

COVERING_RADIUS: float = 1.0 / SQRT_3
"""ρ = 1/√3 ≈ 0.577 — max distance from any point to nearest lattice point."""

SAFE_THRESHOLD: float = COVERING_RADIUS / 2.0
"""ρ/2 ≈ 0.289 — below this, snap is guaranteed safe."""

# ---------------------------------------------------------------------------
# Dodecet encoding (12 nearest-neighbor directions on A₂)
# ---------------------------------------------------------------------------

DODECET_DIRECTIONS: list[tuple[int, int]] = [
    (1, 0), (0, 1), (-1, 1), (-1, 0), (0, -1), (1, -1),
    (2, -1), (1, -2), (-1, -1), (-2, 1), (-1, 2), (1, 1),
]
"""The 12 minimal nonzero vectors of the A₂ lattice."""

# 48 Pythagorean directions (exact angles with rational sin/cos)
# log2(48) = 5.585 bits — maximum information per bit for 16-bit integers
DIRECTION_COUNT: int = 48
DODECET_COUNT: int = 12


# ---------------------------------------------------------------------------
# Core types
# ---------------------------------------------------------------------------

@dataclass(frozen=True, slots=True)
class A2Point:
    """A point on the A₂ (Eisenstein) lattice: a·1 + b·ω.

    Attributes
    ----------
    a : int
        Coefficient of basis vector 1.
    b : int
        Coefficient of basis vector ω = e^{2πi/3}.
    """
    a: int
    b: int

    def __add__(self, other: A2Point) -> A2Point:
        return A2Point(self.a + other.a, self.b + other.b)

    def __sub__(self, other: A2Point) -> A2Point:
        return A2Point(self.a - other.a, self.b - other.b)

    def __neg__(self) -> A2Point:
        return A2Point(-self.a, -self.b)

    def __repr__(self) -> str:
        return f"A2Point(a={self.a}, b={self.b})"

    def norm_sq(self) -> int:
        """Squared Eisenstein norm: a² - ab + b².

        This is always non-negative and equals |z|² where
        z = a + bω in the complex plane.
        """
        return self.a * self.a - self.a * self.b + self.b * self.b

    def to_complex(self) -> tuple[float, float]:
        """Convert to Cartesian (x, y) in the complex plane."""
        x = self.a + self.b * OMEGA_RE
        y = self.b * OMEGA_IM
        return (x, y)


# ---------------------------------------------------------------------------
# Core operations
# ---------------------------------------------------------------------------

def snap(x: float, y: float) -> tuple[A2Point, float]:
    """Snap a point (x, y) to the nearest A₂ lattice point.

    Parameters
    ----------
    x : float
        Real coordinate.
    y : float
        Imaginary coordinate.

    Returns
    -------
    Tuple[A2Point, float]
        The nearest lattice point and the quantization error.

    Notes
    -----
    Error is guaranteed to be ≤ ρ = 1/√3 ≈ 0.577 by the covering property.

    The origin snap(0, 0) returns (A2Point(0, 0), 0.0) — zero error by
    definition, since the origin is itself a lattice point.

    Examples
    --------
    >>> pt, err = snap(0.5, 0.3)
    >>> err <= 1.0 / math.sqrt(3)
    True
    """
    # Input validation
    for name, val in (("x", x), ("y", y)):
        if not isinstance(val, (int, float)):
            raise TypeError(
                f"snap() argument '{name}' must be a number, got {type(val).__name__}"
            )
        if isinstance(val, float) and (math.isnan(val) or math.isinf(val)):
            raise ValueError(
                f"snap() argument '{name}' must be finite, got {val}"
            )

    # Convert Cartesian to lattice coordinates
    # z = x + iy = a + bω = a + b(-1/2 + i√3/2)
    # x = a - b/2,  y = b√3/2
    # b = 2y/√3,  a = x + b/2
    b_f = y / OMEGA_IM  # = 2y/√3
    a_f = x + b_f * 0.5

    # Round to nearest integers
    a = round(a_f)
    b = round(b_f)

    # Check 6 candidates for closest lattice point
    best = A2Point(a, b)
    best_err = _distance_to(x, y, best)

    for da, db in [(1, 0), (-1, 0), (0, 1), (0, -1), (1, -1), (-1, 1)]:
        candidate = A2Point(a + da, b + db)
        err = _distance_to(x, y, candidate)
        if err < best_err:
            best = candidate
            best_err = err

    return (best, best_err)


def soft_snap(x: float, y: float, epsilon: float = 0.0) -> tuple[tuple[float, float], float, A2Point]:
    """Snap with continuous softness control via ε-interpolation.

    Interpolates between the original point (ε=1, free) and the
    exact lattice snap (ε=0, rigid):

        soft_snap(x, ε) = (1-ε) * snap(x) + ε * x

    Parameters
    ----------
    x : float
        Real coordinate.
    y : float
        Imaginary coordinate.
    epsilon : float
        Softness parameter in [0, 1].
        - 0.0 : exact snap (current ``snap()`` behaviour)
        - 0.15: mostly snapped, slight drift
        - 0.5 : loosely attracted to lattice
        - 1.0 : free (no snap, returns original point)

    Returns
    -------
    Tuple[Tuple[float, float], float, A2Point]
        ((soft_x, soft_y), error, snapped_point) where
        (soft_x, soft_y) is the softened point, *error* is the
        Euclidean distance to the exact lattice point, and
        *snapped_point* is the exact lattice point.

    Raises
    ------
    ValueError
        If *epsilon* is not in [0, 1].

    Examples
    --------
    >>> (xy, err, pt) = soft_snap(0.5, 0.3, epsilon=0.0)
    >>> pt2, err2 = snap(0.5, 0.3)
    >>> abs(err - err2) < 1e-12
    True
    >>> (xy, _, _) = soft_snap(0.5, 0.3, epsilon=1.0)
    >>> abs(xy[0] - 0.5) < 1e-12 and abs(xy[1] - 0.3) < 1e-12
    True
    """
    if not isinstance(epsilon, (int, float)):
        raise TypeError(
            f"epsilon must be a number, got {type(epsilon).__name__}"
        )
    if math.isnan(epsilon) or math.isinf(epsilon):
        raise ValueError(f"epsilon must be finite, got {epsilon}")
    if not 0.0 <= epsilon <= 1.0:
        raise ValueError(
            f"epsilon must be in [0, 1], got {epsilon}"
        )

    # Exact snap
    snapped, err = snap(x, y)

    # At ε=1, return the original point unchanged
    if abs(epsilon - 1.0) < 1e-15:
        return ((x, y), err, snapped)

    # At ε=0, return exact snap
    if epsilon == 0.0:
        sx, sy = snapped.to_complex()
        return ((sx, sy), err, snapped)

    # Interpolate: (1-ε)*snapped + ε*original
    sx, sy = snapped.to_complex()
    soft_x = (1.0 - epsilon) * sx + epsilon * x
    soft_y = (1.0 - epsilon) * sy + epsilon * y

    # Recompute distance from soft point to lattice point
    dx = soft_x - sx
    dy = soft_y - sy
    soft_err = math.sqrt(dx * dx + dy * dy)

    return ((soft_x, soft_y), soft_err, snapped)


def covering_radius() -> float:
    """Return the A₂ covering radius ρ = 1/√3."""
    return COVERING_RADIUS


def is_safe(error: float) -> bool:
    """Check if quantization error is within the safe threshold.

    Safe means error < ρ/2, which guarantees the snap is unambiguous
    (no closer lattice point exists within half the covering radius).
    """
    return error < SAFE_THRESHOLD


def norm_sq(point: A2Point) -> int:
    """Compute squared Eisenstein norm a² - ab + b²."""
    return point.norm_sq()


def decode_dodecet(index: int) -> A2Point:
    """Decode a dodecet index (0-11) to an A₂ direction vector.

    Parameters
    ----------
    index : int
        Dodecet index, 0 ≤ index < 12.

    Returns
    -------
    A2Point
        The direction vector.

    Raises
    ------
    ValueError
        If index is not in [0, 11].
    """
    if not 0 <= index < DODECET_COUNT:
        raise ValueError(f"Dodecet index must be 0-{DODECET_COUNT - 1}, got {index}")
    a, b = DODECET_DIRECTIONS[index]
    return A2Point(a, b)


def encode_dodecet(point: A2Point) -> int:
    """Encode an A₂ direction vector to a dodecet index.

    Parameters
    ----------
    point : A2Point
        A short lattice vector.

    Returns
    -------
    int
        Dodecet index 0-11.

    Raises
    ------
    ValueError
        If the point is not one of the 12 minimal vectors.
    """
    t = (point.a, point.b)
    try:
        return DODECET_DIRECTIONS.index(t)
    except ValueError as exc:
        raise ValueError(f"({point.a}, {point.b}) is not a dodecet direction") from exc


def vector48_encode(angle: float) -> int:
    """Quantize an angle to one of 48 Pythagorean directions.

    The 48 directions are evenly spaced at 7.5° intervals (360°/48).

    Parameters
    ----------
    angle : float
        Angle in radians.

    Returns
    -------
    int
        Direction index 0-47.
    """
    two_pi = 2.0 * math.pi
    # Normalize to [0, 2π)
    normalized = angle % two_pi
    index = round(normalized / two_pi * DIRECTION_COUNT) % DIRECTION_COUNT
    return index


def vector48_decode(index: int) -> float:
    """Decode a Pythagorean direction index to an angle.

    Parameters
    ----------
    index : int
        Direction index 0-47.

    Returns
    -------
    float
        Angle in radians.
    """
    if not 0 <= index < DIRECTION_COUNT:
        raise ValueError(f"Direction index must be 0-{DIRECTION_COUNT - 1}, got {index}")
    return index * 2.0 * math.pi / DIRECTION_COUNT


def holonomy_product(directions: list[int]) -> int:
    """Compute holonomy around a cycle of directions.

    The holonomy is the sum of direction vectors modulo 48.
    If the result is 0, the cycle is consistent (holonomy-free).

    Parameters
    ----------
    directions : List[int]
        List of direction indices (0-47) forming a cycle.

    Returns
    -------
    int
        Holonomy (sum mod 48). 0 means consistent.

    Notes
    -----
    An empty list returns 0 — a trivial (empty) cycle has no holonomy.
    """
    if not directions:
        return 0
    return sum(directions) % DIRECTION_COUNT


def is_consistent(directions: list[int]) -> bool:
    """Check if a cycle of directions is holonomy-free (consistent).

    Parameters
    ----------
    directions : List[int]
        List of direction indices forming a cycle.

    Returns
    -------
    bool
        True if holonomy is zero (cycle is consistent).

    Notes
    -----
    An empty list returns True — an empty cycle is trivially consistent.
    """
    return holonomy_product(directions) == 0


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _distance_to(x: float, y: float, point: A2Point) -> float:
    """Euclidean distance from (x, y) to a lattice point."""
    px, py = point.to_complex()
    dx = x - px
    dy = y - py
    return math.sqrt(dx * dx + dy * dy)
